name: Initialize

# Controls when the workflow will run
on:
    create:
    #If for some reason the action is not initiated after creating repo
    workflow_dispatch:

jobs:
  Init:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Edit package.json
        env:
         ORGANIZATION_NAME : ${{ github.repository_owner }}
         PACKAGE_NAME : ${{ (github.event.repository.name | tr '-' '') }}         
         
         DISPLAY_NAME : ${{ github.event.repository.name }}
         
         NAME : com.${ORGANIZATION_NAME}.${PACKAGE_NAME} | tr '[:upper:]' '[:lower:]'
        run: |
         sed -i "s/com.organization.package/$NAME/" package.json
         sed -i "s/Package/$DISPLAY_NAME/" package.json
         
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
