# This is a basic workflow to help you get started with Actions

name: Initialize

# Controls when the workflow will run
on:
    create:

jobs:
  Init:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Edit package.json
        env:
         PACKAGE_NAME : ${{ github.event.repository.name }}
         #COMPANY_NAME : ${{ github.repository_owner }}
        run: |
         sed -i 's/Package/$PACKAGE_NAME/' package.json
        #sed -i 's/organization/$COMPANY_NAME/' package.json
         
      - name: Push to remote
        run: |
         git config user.name "${{ secrets.GH_USER }}"
         git config user.email "${{ secrets.GH_MAIL }"
         git add -A
         git commit -m "Initialized"
         git push
      
      #- name: Rename Assembly Definition Files
      #  env:
      #   REPO_NAME: ${{ github.event.repository.name }}
      #  run: |
      #   echo $REPO_NAME
