name: Initialize

# Controls when the workflow will run
on:
    create:
    workflow_dispatch:
        inputs:
            organizationName:
                description: "Organization Name"
            packageName:
                description: "Package Name"
jobs:
  Init:
    # Run job if workflow was manually triggered or if repo was created in an Organization
    if: github.event_name == 'workflow_dispatch' || github.repository_owner != github.actor
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Gather Info
        run: |
            
            echo "{organization_name}=${{ github.repository_owner }} >> $GITHUB_ENV
            echo "{package_name}=${{ github.event.repository.name }} >> $GITHUB_ENV
        
            if [ "${{ github.event_name }}" = "workflow_dispatch" ]; 
            then
                if [ -n "${{ github.event.inputs.organizationName }}" && -z "${{ github.event.inputs.packageName }}" ]
                then
                    echo "{organization_name}=${{ github.event.inputs.organizationName }} >> $GITHUB_ENV
                    echo "{package_name}=${{ github.event.inputs.packageName }} >> $GITHUB_ENV
                fi
            fi
      
      - name: Run Init.sh script
        run: |
         chmod +x ./Init.sh
         ./Init.sh "${{ env.organization_name }}" "${{ env.package_name }}"
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
         message: Initialized Package
         committer_name: GitHub Actions
         committer_email: 41898282+github-actions[bot]@users.noreply.github.com
