name: Initialize

# Controls when the workflow will run
on:
    create:
    #If for some reason the action is not initiated after creating repo
    workflow_dispatch:

env:
 REPO_NAME: ${{ github.event.repository.name }}
 OWNER_NAME: ${{ github.repository_owner }} 

jobs:
  Init:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set Organization and Package Name
        run: |
         "ORGANIZATION_NAME=$($OWNER_NAME | tr -d '-')" >> $GITHUB_ENV
         "PACKAGE_NAME=$($REPO_NAME | tr -d '-')" >> $GITHUB_ENV
      
      - name: Set Full Name
        run: |
         "FULL_NAME=$(echo com.$ORGANIZATION_NAME.$PACKAGE_NAME | tr '[:upper:]' '[:lower:]'" >> $GITHUB_ENV
      
      - name: Set Display Name
        run: |
         "DISPLAY_NAME=$(echo $REPO_NAME | tr '-' ' ')" >> $GITHUB_ENV
      
      - name: Print Envs
        run: |
         echo "${{ env.ORGANIZATION_NAME }}"
         echo "${{ env.PACKAGE_NAME }}"
         echo "${{ env.FULL_NAME }}"
         echo "${{ env.DISPLAY_NAME }}"
         
      #- name: Edit package.json
      #  env:
      #   OWNER_NAME : ${{ github.repository_owner }}
      #   PACKAGE_NAME : ${{ github.event.repository.name }}
      #   NAME : com.${ORGANIZATION_NAME}.${PACKAGE_NAME} | tr '[:upper:]' '[:lower:]'
      #  run: |
      #   sed -i "s/com.organization.package/$NAME/" package.json
      #   sed -i "s/Package/$DISPLAY_NAME/" package.json
         
      #- name: Add & Commit
      #  uses: EndBug/add-and-commit@v9
      #  with:
      #    default_author: github_actions
